### ISSUE TITLE
Error Creating remote URL

### ISSUE THREAD

**Issue by Ropscot** [whitesoup12/remote-falcon-issues#2]
Found remote token ######################
Creating Remote URL
Waiting for script to execute
Error occured when creating Remote URL

**Comment by whitesoup12** [comment]
@Ropscot, can you try this in FPP? Go to Help -> SSH Shell, putt in fpp as the user and falcon as the password, then paste the below code and hit Enter. Let me know if you get an error or if it succeeds.
`ssh -R 80:localhost:80 ssh.localhost.run`

**Comment by Ropscot** [comment]
It doesn't do anything just keeps blinking but if I click on either link it
pulls up fpp.

**Comment by whitesoup12** [comment]
@Ropscot thats good. Have you tried rebooting FPP completely?

**Comment by Ropscot** [comment]
Yes same error.

**Comment by tbistr69** [comment]
I am having the same problem as above. I did what you have suggested about and I am still getting the error

**Comment by tbistr69** [comment]
![Screenshot 2020-01-22 06 45 07](https://user-images.githubusercontent.com/60179738/72891806-12ddf400-3ce3-11ea-9574-b5dfbe06251d.png)
![Screenshot 2020-01-22 06 45 30](https://user-images.githubusercontent.com/60179738/72891816-15d8e480-3ce3-11ea-9cbb-61bd5d93d851.png)

**Comment by whitesoup12** [comment]
@tbistr69 looks like yours created the url? What do the Remote Falcon Plugin logs show? And does it not do anything when you click the Refresh Control Panel?

**Comment by whitesoup12** [comment]
@Ropscot still trying to figure out what’s going on with yours.

**Comment by Ropscot** [comment]
Mine works now. I logged in with my phone and restarted fpp and it worked
so im not sure if the pc i was using caused the issue or not.

**Comment by whitesoup12** [comment]
@Ropscot, well that is definitely weird. Any chance you could try it on the PC again? Everything happens within FPP, so where you do it shouldn't matter, unless it's a firewall issue which we know it isn't since you were able to run that command above and generate a URL.

**Comment by Ropscot** [comment]
I think I figured it out. I believe octoprint was causing the issue. I
plugged in octoprint and it failed. unplugged and it works..

**Comment by whitesoup12** [comment]
@Ropscot, well then, I wouldn't have guessed that in a million years. :)

@tbistr69. do you by chance have a 3D printer as well?

**Comment by Ropscot** [comment]
Yes I do an ender 5.

**Comment by Ropscot** [comment]
Any reason why this shows up on the show page?

**Comment by whitesoup12** [comment]
@Ropscot is there supposed to be an image?

**Comment by Ropscot** [comment]
Yes none of my songs or playlist show. Just a bunch of letters.

**Comment by whitesoup12** [comment]
@Ropscot what's your show name?

**Comment by Ropscot** [comment]
Hammondfamilylightshow

**Comment by whitesoup12** [comment]
@Ropscot, just pushed a fix for it.

**Comment by tbistr69** [comment]
I do not, sorry- haven’t been at home all day, will check in it when I get home!

**Comment by Ropscot** [comment]
hmm still showing the same for me

**Comment by whitesoup12** [comment]
@Ropscot try doing Ctrl/Cmd + Shift + R to do a hard refresh.

**Comment by Ropscot** [comment]
No still shows all the same letters but no songs or playlist. I have
several playlist created and nothing shows. do I need to do anything with
fpp schedule?

**Comment by whitesoup12** [comment]
@Ropscot, I see the issue now. I should be able to fix this tomorrow. As for the original issue with the URL not getting created, are you still having that issue? If not, I'm going to close this issue. Also going to open a new one for the weird issue you're seeing on your homepage.

**Comment by Ropscot** [comment]
Hey thanks nope no issue with the url being created since I took the
octoprint offline. Thanks for all your help.

**Comment by whitesoup12** [comment]
@Ropscot, I think I got the weird issue fixed with the big list of characters. That bug is tracked [here](https://github.com/whitesoup12/remote-falcon-issues/issues/3). However, I did open another issue [here](https://github.com/whitesoup12/remote-falcon-issues/issues/4) because it looks like your plugin in sending blank URLs

**Comment by Ropscot** [comment]
I will take a look at it when I get home around 2pm est.
Thanks

**Comment by Ropscot** [comment]
letters are still there

**Comment by Ropscot** [comment]
also If I enable the jukebox then I get the remote error

**Comment by whitesoup12** [comment]
@Ropscot, looks like one of those fun issues where everything works when I run it locally but not from the main site. Also, can we move this conversation to the open bug I'm tracking for this issue [here](https://github.com/whitesoup12/remote-falcon-issues/issues/3)?
