### ISSUE TITLE
If FPP is offline the HTML response tries to render in the list

### ISSUE THREAD

**Issue by whitesoup12** [whitesoup12/remote-falcon-issues#3]
If FPP is offline the HTML response tries to render in the list.

**Comment by whitesoup12** [comment]
@Ropscot, for visibility.

**Comment by whitesoup12** [comment]
@Ropscot, I believe I got this fixed now. Can you verify?

**Comment by Ropscot** [comment]
Says show is offline. But I can log into control panel.

**Comment by whitesoup12** [comment]
@Ropscot, I still have the other open issue regarding that. I'll close this one now.
