### ISSUE TITLE
Remote Falcon Plugin saving URLs as blank

### ISSUE THREAD

**Issue by whitesoup12** [whitesoup12/remote-falcon-issues#4]

**Comment by whitesoup12** [comment]
@Ropscot, if you restart FPPD does it generate a URL for you now?

**Comment by Ropscot** [comment]
Yes

**Comment by whitesoup12** [comment]
@Ropscot, can you send the logs from the Remote Flacon Plugin? All I'm seeing in the database for your URL is "v3.5".

**Comment by Ropscot** [comment]
Found remote token 55F1VD1gJK0MR6IUUBnUgepRx
Creating Remote URL
Waiting for script to execute
Created Remote URL v3.0


Sending Remote URL to Remote Falcon
POST: {"remoteKey":"55F1VD1gJK0MR6IUUBnUgepRx","remoteURL":"v3.0\n\n"}
Successfully saved Remote URL to Remote Falcon

**Comment by whitesoup12** [comment]
@Ropscot, very helpful, thank you! I'll try to get this fixed up. I see other users having the same problem.

**Comment by Ropscot** [comment]
Great thanks!

**Comment by whitesoup12** [comment]
@Ropscot can you go to Plugin Manager and update the Remote Falcon plugin then restart FPPD? I think I found the issue.

**Comment by Ropscot** [comment]
That fixed it!

**Comment by whitesoup12** [comment]
Oh yeah! Thanks for your help and your patience!

**Comment by Ropscot** [comment]
Thankyou!
