### ISSUE TITLE
Webpage hangs on iOS devices

### ISSUE THREAD

**Issue by travcam** [whitesoup12/remote-falcon-issues#5]
When the song selection page loads on an iOS 13.3 device (I’ve tried three) the page hangs and has extreme latency.  The page often fails to scroll and when a song is selected it is slow to confirm.   In contrast, on an android OS, pages load fine and responses to song selection are nearly immediate.   Tested on 2x iPhone X, iPad Air2, and Samsung S9.

**Comment by travcam** [comment]
I tried making a screen recording of this, and apparently whatever is causing it is hanging the processor as the recording hangs while the issue occurs.

**Comment by whitesoup12** [comment]
@travcam is it the playlist list on the viewer page or the control panel?

**Comment by travcam** [comment]
playlist list
