### ISSUE TITLE
generated url incorrect?

### ISSUE THREAD

**Issue by schulzfamilylights** [whitesoup12/remote-falcon-issues#6]
downloaded plugin
installed
configured
restart fpp

logs
			Starting fpp_remote.php at 04:03:39
Found remote token _removed_
Creating Remote URL
Waiting for script to execute
Created Remote URL https://gain.
Sending Remote URL to Remote Falcon
POST: {"remoteKey":"_removed_","remoteURL":"https:\/\/gain."}
Successfully saved Remote URL to Remote Falcon

remote url does not make sense.. and remote fpp thinks fpp is offline.. even though it is up and running

**Comment by whitesoup12** [comment]
Can you try rebooting FPP as well? Also make sure your FPP has internet access.

**Comment by schulzfamilylights** [comment]
rebooted fpp, went into plugin.. still shows same url.. restarted fpp again. still the https://gain.. 
i downloaded the plugin from within fpp so i can get out to internet fine

**Comment by whitesoup12** [comment]
@schulzfamilylights, try seeing if it will work manually first. Open up SSH Shell in FPP (user is fpp, password falcon) and run this command:
`ssh -R 80:localhost:80 uxA2EZHFAwMYxtAltYYO7IL45@ssh.localhost.run -o ServerAliveInterval=60`

**Comment by schulzfamilylights** [comment]
You can access the UI by typing "http://fpp.local/" into a web browser.
fpp@FPP:~ $ ssh -R 80:localhost:80 uxA2EZHFAwMYxtAltYYO7IL45@ssh.localhost.run -o ServerAliveInterval=60
                                                                                                                                                                                                                                                                                                                                             
===============================================================================                                                                                                                                                                                                                                                              
Welcome to localhost.run!                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                             
Head over to https://twitter.com/localhost_run and give us a follow for the                                                                                                                                                                                                                                                                  
hottest SSH port forwarded local dev env news.                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                             
**You're going to need a SSH key to access this service soon.**                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                             
If you don't know what this is pls don't panic, you're smart, you've got this.                                                                                                                                                                                                                                                               
Github has a great howto, follow along with it to get prepared for the change:                                                                                                                                                                                                                                                               
https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                             
Why is this happening you ask? Behind the scenes we've been hard at work.                                                                                                                                                                                                                                                                    
There's bug fixes, stability improvements and soon, new features, some of which                                                                                                                                                                                                                                                              
require that SSH key we mentioned. Probably a new website too, for peeps who                                                                                                                                                                                                                                                                 
don't yet know the joys of using SSH to read this. Watch this space...                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                             
**If you see a message below telling you that your hostname is already in use**                                                                                                                                                                                                                                                              
** try a different username like this:**                                                                                                                                                                                                                                                                                                     
**`ssh -R localhost:80:localhost:8080 random-string@ssh.localhost.run`**                                                                                                                                                                                                                                                                     
===============================================================================                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                             
Warning: remote port forwarding failed for listen port 80                                                                                                                                                                                                                                                                                    
{"domain": "uxa2ezhfawmyxtaltyyo7il45-a6827e3c.localhost.run", "listen_port": 80, "status": "error", "error_code": "DomainInUse", "message": "uxa2ezhfawmyxtaltyyo7il45-a6827e3c.localhost.run is already in use, try a different domain"}

**Comment by whitesoup12** [comment]
@schulzfamilylights thats good news. Means the connection is working. Last attempt might be to delete the plugin, reboot FPP (to close the connection) then try it again.

**Comment by schulzfamilylights** [comment]
ok, i will give that a shot and let you know

**Comment by schulzfamilylights** [comment]
same problem.. still generates the url https://gain

**Comment by schulzfamilylights** [comment]
do i need to open anything in my firewall for the communication? or what is occurring when it generates the url? what communication is needed?

**Comment by whitesoup12** [comment]
It’s the same command I had you run manually, except it does it from a script and sends the generated URL to Remote Falcon. The URL is pulled from the output of the command you ran, and I don’t see the word “gain” anywhere in the output, so that’s confusing. Typically the URL you connect to is printed last in the output, as long as it’s a new URL (meaning the connection isn’t already open). Everyone’s PC is different and FPP setups vary greatly, so this step is difficult to debug. I need to get better logging and errors I can view on my end.

**Comment by schulzfamilylights** [comment]
so, my fpp user password is not 'falcon' are u hard-coding that somewhere?

**Comment by whitesoup12** [comment]
Ah, yes. Are you using an admin password or is it just the shell password that you changed? I can easily put in a fix to allow you to specify the shell password

**Comment by schulzfamilylights** [comment]
i changed the fpp password.. habits.. lol  would be great if we can set that as a parameter 
in remote falcon

**Comment by whitesoup12** [comment]
I can definitely do that! Thanks!

**Comment by schulzfamilylights** [comment]
awesome, thank you! this thing will be great.. my nieghbors are already excited for the jukebox feature.. lol

**Comment by schulzfamilylights** [comment]
so i set the password for fpp back to 'falcon', deleted plugin, rebooted fpp, reinstalled and configured plugin.. still creating the https://gain.. i noticed it actually first shows https://3.6 (above script window) while scripts are still running then changes to https://gain in log when complete

**Comment by whitesoup12** [comment]
Are you running FPP 3.6? It should work on any recent version, but I've been testing with 4.0. Can you open the shell again and run this? It's the file that saves the output from the connection and where the URL is retrieved from.
`tail /home/fpp/media/plugins/remote-falcon/remote_url.txt`

**Comment by schulzfamilylights** [comment]
so i did a sudo passwd earlier and reset to falcon.. but it apparently didnt take.. (still has old password) but the remote_url.txt shows 'permission denied'.. let me see if can get password reset to falcon and verify it first.. then try again.. I am using 3.6.2 btw

**Comment by schulzfamilylights** [comment]
ok so got the password reset to 'falcon' and it works.. it can connect and generates a proper url.. ill wait to reset password again ocne you update the code - thank you

**Comment by whitesoup12** [comment]
I’ll update you once the new plugin is available.
